# Generated by Django 5.2.15 on 2026-07-07 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('emergency_type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('CARDIAC', 'Cardiac Emergency'), ('BREATHING', 'Breathing Problem'), ('BLEEDING', 'Severe Bleeding'), ('NEUROLOGICAL', 'Neurological Emergency'), ('PREGNANCY', 'Pregnancy Emergency'), ('OTHER', 'Other Emergency')], max_length=30)),
                ('location', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('ambulance_required', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MODERATE', 'Moderate')], default='HIGH', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('AMBULANCE_DISPATCHED', 'Ambulance Dispatched'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
