# Generated by Django 5.2.15 on 2026-07-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_hospitalbranch_doctorprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
