# Generated by Django 5.2.15 on 2026-07-07 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('AWAITING_TESTS', 'Awaiting Tests'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('BLOOD', 'Blood Test'), ('URINE', 'Urine Test'), ('XRAY', 'X-Ray'), ('ULTRASOUND', 'Ultrasound'), ('ECG', 'ECG'), ('CT_SCAN', 'CT Scan'), ('MRI', 'MRI'), ('OTHER', 'Other')], max_length=30)),
                ('test_name', models.CharField(max_length=150)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('REPORT_READY', 'Report Ready'), ('REVIEWED', 'Reviewed')], default='ORDERED', max_length=30)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_orders', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
    ]
