# Generated by Django 5.2.15 on 2026-07-07 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_testorder_fee_testbill_testbillitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_status', models.CharField(choices=[('NORMAL', 'Normal'), ('ABNORMAL', 'Abnormal'), ('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('INCONCLUSIVE', 'Inconclusive')], max_length=20)),
                ('result_value', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=150)),
                ('findings', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_result', to='appointments.testorder')),
                ('tested_by', models.ForeignKey(limit_choices_to={'role': 'LAB_TECHNICIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_lab_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
