# Generated by Django 5.2.15 on 2026-07-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_labresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='test_id',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
