# Generated by Django 5.2.15 on 2026-07-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_testorder_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labresult',
            name='whatsapp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
